In [62]:
import tensorflow as tf
from tensorflow import nn as tfnn
import numpy as np

In [2]:
# creating List of random data 
rand_data = np.random.randint(1000,size=10000)

In [3]:
rand_data

array([122, 162, 772, ..., 256, 966, 222])

## Declaring Tensors

* They are primary data structures that TensorFlow uses to operate on the computational graphs 
* Declare them as variables and feed them to placeholders
* There are 4 types of Tensors:
    * **Fixed Tensor**
    * **Tensors of similar shape**
    * **Sequence Tensors**
    * **Random Tensors**

In [4]:
row_dim = 4
col_dim = 4

### Fixed Tensor

In [5]:
# Creating Zero filled Tensor
zero_tsr = tf.zeros([row_dim,col_dim])

In [6]:
# Creating a One filled Tensor
ones_tsr = tf.ones([row_dim,col_dim])

In [7]:
# Creating a constant filled Tensor
filled_tsr = tf.fill([row_dim,col_dim],42)

In [8]:
# Creating tensor out of existing constant
constant_tsr = tf.constant([1,2,3])

# tf.constant can also be used to broadcast constant 
# into an array mimcking the behaviour of tf.fill()
# tf.constant(42,[row_dim,col_dim])

## Tensor with similar shape

We can initialize tensors based on shape of other tensors

In [9]:
zero_similar = tf.zeros_like(constant_tsr)

In [10]:
ones_similar = tf.ones_like(constant_tsr)

## Sequence Tensors

* Tensor flow allows us to specify tensor that contain defined intervals

In [11]:
# The following function behaves like range() or numpys linspace() 
# This example gives [10.0, 11.0, 12.0]
linear_tsr = tf.linspace(start=10.0,stop=12.0,num=3)

In [12]:
# Like range() 
# result is [6, 9, 12]
integer_seq_tsr = tf.range(start=6,limit=15,delta=3)

## Random Tensor
* Following tensors generate form of random numbers 

In [13]:
# Generated random numbers from uniform distributions
# is of the form minval <= x < maxval (exclusive)
randunif_tsr = tf.random_uniform([row_dim, col_dim], minval=0, maxval=1)

In [14]:
# Generate from normal distribution
randnorm_tsr = tf.random_normal([row_dim,col_dim], mean=0.0, stddev=1.0)

In [15]:
# Normal random values that are assured within certain bounds
# this function always picks normal values within two stddev of specified mean 
randnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)

In [16]:
# If interested in randomizing entries of arrays
# these two functions helps us achieve that
# shuffled_output = tf.random_shuffle(input_tensor)
# cropped_output = tf.random_crop(input_tensor, crop_size)

In [17]:
# sometimes interested in randomly cropping the image of size (height,width,3)
# 3 color spectrum
# cropped_image = tf.random_crop(my_image, [height/2, width/2, 3])

-

# Placeholders and Variables

* Once we have declared tensors, we would like to create corresponding variables by wrapping in Variable()
* Eg. my_var = tf.Variable(tf.zeroes(row_dim,col_dim))
* we are not limited to built-in functions
    * we can use numpy array to python list or constant
    * convert it to a tensor using convert_to_tensor()
* Most important distinction to make with Data is whether it is a placeholder or a variable
* **Variables** are the parameters of algorithms and TensorFlow keeps track on how to change these to optimize the algo
* **Palceholders** are objects that allow you to feed in data of specific type and shape and depend on the result of the computational graph

* Main way of creating a variable is by using function Variable() that takes in tensor as argument and outputs a variable
* Once we declare a variable we still need to initialize it to place it with corresponding method on computational graph 
* TensorFlow must be informed when it can initialize the variables 
* While Each variable has a initializer method most common way to do it is use *helper* function 
    * *tf.global_variable_initializer()*

In [19]:
my_var = tf.Variable(tf.zeros([row_dim,col_dim]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

* Placeholder are holding position for data to be fed into the graph 
* They get their data from feed_dict argument in the session
* Atleast one operation must be performed on the placeholder to put it in the graph 
* Example below :
    * Initialize the graph (sess)
    * Declare placeholder x 
    * Define y as an identity operation on x (basically returns x as it is)
    * create data x_vals to feed into placeholder
    * run the identity operation

In [20]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict={x: x_vals})

array([[ 0.95166528,  0.70336717],
       [ 0.6986872 ,  0.49709058]], dtype=float32)

# Working with Matrices

### Creating Matrix

We can create two dimensional matrices from numpy arrays or nested list. We can also use tensor creation function and specify the dimensional shape as zeros(), ones(), truncated_normal() etc. TensorFlow also allows us to create diagonal matrix from one-dimensional array list with function diag() 

In [30]:
identity_matrix = tf.diag([1.0,1.0,1.0])
A = tf.truncated_normal([2,3])
B = tf.fill([2,3], 5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]))

In [31]:
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
print(sess.run(A))

[[ 0.42246732  0.12971412  0.95483977]
 [-1.23782456  1.10262001 -1.60466278]]


In [33]:
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [37]:
print(sess.run(C))

[[ 0.56389999  0.79629529]
 [ 0.65979457  0.99815464]
 [ 0.36476254  0.07206917]]


In [35]:
print(sess.run(D))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


#### Addition, Subtraction, Multiplication

In [40]:
# Adding two matrices 
print(sess.run(A+B))

[[ 3.28768134  4.84680271  4.50768471]
 [ 6.45017672  6.00239658  3.14912653]]


In [41]:
# Subtracting two matrices
print(sess.run(B-B))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [43]:
# Multiplying two matrices 
# Matmul() also has an argument to specify whether or not to transpose the argument before multi
print(sess.run(tf.matmul(B,identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [44]:
# To transpose the matrix 
print(sess.run(tf.transpose(D)))

[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]]


In [45]:
# To calculate the determinant 
print(sess.run(tf.matrix_determinant(D)))

6.66133814775e-16


In [46]:
# To calculate the inverse 
# The matrix inverse is based on Cholesky decomposition
print(sess.run(tf.matrix_inverse(D)))

[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]


In [47]:
# For Eigenvalues and Eigenvectors
# Ouputs the eigenvalues in the first row and the subsequent vectors in the remaining 
print(sess.run(tf.self_adjoint_eig(D)))

(array([ -3.15746784,  -0.67276795,  18.8302358 ]), array([[-0.80238891, -0.43402538,  0.40962667],
       [-0.16812656,  0.82296167,  0.54264865],
       [ 0.57263033, -0.36654613,  0.73330651]]))


## Some TensorFlow operations

TensorFlow has standard operations on tensors - **add(), sub(), mul(), div()**.
Note that *div()* here returns floor integer value of the result as in Python2 to get the Python3 like result use *truediv()*


In [48]:
print(sess.run(tf.div(3,4)))

0


In [49]:
print(sess.run(tf.truediv(3,4)))

0.75


In [50]:
# Using floats to get integer division to the nearest rounded down integer
print(sess.run(tf.floordiv(3.0,4.0)))

0.0


In [51]:
# Get the remainder after the division 
# mod()
print(sess.run(tf.mod(22.0,5.0)))

2.0


In [54]:
# Cross product between two tensors is achieved by the cross()
# It only accepts two three-dimensional vectors
print(sess.run(tf.cross([1.,0.,0.],[0.,1.,0.])))

[ 0.  0.  1.]


### These are some of the other math function that tensor flow provides

<img align='center' src='pynb_image/tf_math_func.png'>

#### These are some special math functions that are used in Machine Learning 

<img align='center' src='pynb_image/tf_special_func.png'>

In [56]:
# It is important to know what functions are available to us so we can generate different custom functions based on this 
# Example tangent(pi/4) = 1

print(sess.run(tf.div(tf.sin(3.1416/4),tf.cos(3.1416/4))))

1.0


## Implementing the Activation Function

* When you use Neural Networks we will be using activation functions regularly as they are mandatory part of it
* The goal is to adjust the weights and bias
* Few main concept of activation function is that they introduce a non-linearity into the graph while normalizing the output
* The activation function lives in **Neural Netwrok (nn)** library in TensorFlow. 
* we can also design our own beside using TensorFlows builtin activation function 
* import predefined functions using tensorflow.nn

In [66]:
# Rectified linear unit, known as ReLU is the most basic and common way to introduce a non-linearity into NN 
# It is continous but not smooth 
# This function is basically max(0,x)
print(sess.run(tfnn.relu([-3.,3.,10.,-5.,5.])))

[  0.   3.  10.   0.   5.]


In [68]:
# There will be times where we want to cap the linearly increasing part of the preceding ReLU activation function
# We can do this my nesting the max(0,x) function in min() function
# The implementation that TensorFlow has is called ReLU6 defined by min(max(0,x),6)
# This is a version of hard sigmoid function and is computationally faster 
# This will be handy in CNN and RNN

print(sess.run(tfnn.relu6([-3.,3.,5.,10.,-5.,7.])))

[ 0.  3.  5.  6.  0.  6.]


In [73]:
# The sigmoid is the most common continuous function and smooth activation function
# also called Logistic function and is of form 1 / (1+exp(-x))
# It is not often used because it has the tendency to zero out the backpropogation terms during training 

print(sess.run(tfnn.sigmoid([-1.,0.,1.])))

[ 0.26894143  0.5         0.7310586 ]


In [74]:
# Another smooth function is the hypertangent this is pretty similar to the sigmoid function
# Except instead of having between range 0 and 1 its -1 and 1 
# A form of writing that is (exp(x) - exp(-x))/(exp(x)+exp(-x))

print(sess.run(tfnn.tanh([-1.,0.,1.])))

[-0.76159418  0.          0.76159418]


In [75]:
# The softsign function also gets used as an activation function 
# The form of this function is x/(abs(x) + 1)
# This is supposed to be the continous approximation of sign function 

print(sess.run(tfnn.softsign([-1., 0., 1.])))

[-0.5  0.   0.5]


In [76]:
# Another function is softplus function is a smooth version of ReLU function 
# This is of the form log(exp(x)+1)

print(sess.run(tfnn.softplus([-1.,0.,-1])))

[ 0.31326166  0.69314718  0.31326166]


In [78]:
 # The softplus goes to infinity as the input increases whereas the softsign goes to 1 
# As the input gets smaller the softplus approaches 0 and softsign goes to -1

In [80]:
# The Exponential Linear Unit (ELU) is vvery similar to the softplus function
# except the bottom asymptote is -1 instead of 0 
# Form is (exp(x) + 1) if x < 0 else x 

print(sess.run(tfnn.elu([-1., 0., -1.])))

[-0.63212055  0.         -0.63212055]


* Activation function introduces non linearity in Neural Network 
* It is important to note where in the our network we are using activation function 
* If the activation function has range between 0 and 1(Sigmoid) then comp graph can only output values between 0 and 1
* If the activation function is inside and hidden between nodes, then we want to be aware of the effect its range can have on our tensors as we pass them through 
* If for example the tensors are scaled to be +ve then ideally we would choose activation function that preserves variance in the +ve domain 